function createfigure(XData1, YData1, YData2, YData3, Parent1)
%CREATEFIGURE(XData1, YData1, YData2, YData3, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 22-Apr-2024 13:13:26

% Create figure
figure('WindowState','maximized','Tag','ScopePrintToFigure','Color',[1 1 1],...
    'OuterPosition',[-6.2 41.8 1550.4 830.4]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag');
hold(axes1,'on');
colororder([0 0.447058823529412 0.741176470588235;0.850980392156863 0.325490196078431 0.0980392156862745;0.929411764705882 0.694117647058824 0.125490196078431;0.494117647058824 0.184313725490196 0.556862745098039;0.466666666666667 0.674509803921569 0.188235294117647;0.301960784313725 0.745098039215686 0.933333333333333;0.635294117647059 0.0784313725490196 0.184313725490196]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','Gain q1','Tag','DisplayLine1',...
    'LineWidth',3,...
    'Color',[1 1 0.0666666666666667]);

% Create line
line(XData1,YData2,'DisplayName','Gain q2','Tag','DisplayLine2',...
    'LineWidth',3,...
    'Color',[0.0745098039215686 0.623529411764706 1]);

% Create line
line(XData1,YData3,'DisplayName','Gain q3','Tag','DisplayLine3',...
    'LineWidth',3,...
    'Color',[1 0.411764705882353 0.16078431372549]);

% Create ylabel
ylabel('Gain','FontName','Georgia');

% Create xlabel
xlabel('Time (seconds)','FontName','Georgia');

% Create title
title('Controller Output','Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.506034275977092 1.75938684130127]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','FontName','Georgia','FontSize',18,...
    'GridAlpha',0.4,'GridColor',[0 0 0],'TickLabelInterpreter','none','XGrid',...
    'on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels','Position',[134.8 508.4 264 156],...
    'Interpreter','none',...
    'FontSize',16,...
    'EdgeColor',[0 0 0]);

% Create text
text('Tag','TimeOffsetStatus','Parent',Parent1,'Units','pixels',...
    'VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Visible','on');

